# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI (Maven) and CNAB bundle package and publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: |
        mvn -B package --file pom.xml
    - name: CNAB Bundle with porter
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        echo "Removing several directories until dockerignore regression is fixed."
        rm -rf .git/ 
        rm -rf src/
        rm -rf generated-sources/
        rm -rf maven-status
        rm -rf test-classes
        rm -rf classes
        rm -rf generated-test-sources
        rm -rf maven-archiver
        rm -rf surefire-reports
        echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
        curl https://deislabs.blob.core.windows.net/porter/latest/install-linux.sh | bash
        PATH=$PATH:~/.porter
        porter mixins install jq --url https://github.com/squillace/porter-jq/releases/download --version v0.1.0
        porter build
        porter publish


